spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/pedidos
spring.datasource.username=ggregoriodev
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true